//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BhagirathFincareClassLibrary.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class BhagirathFinCareEntities : DbContext
    {
        public BhagirathFinCareEntities()
            : base("name=SqlConnection")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<SuperCallsData> SuperCallsData { get; set; }
        public virtual DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }
        public virtual DbSet<ELMAH_Error> ELMAH_Error { get; set; }
        public virtual DbSet<Holidays> Holidays { get; set; }
        public virtual DbSet<HotStock> HotStock { get; set; }
        public virtual DbSet<Invoice> Invoice { get; set; }
        public virtual DbSet<MarketPrice> MarketPrice { get; set; }
        public virtual DbSet<RecursiveResult> RecursiveResult { get; set; }
        public virtual DbSet<RecursiveUpload> RecursiveUpload { get; set; }
        public virtual DbSet<UserProfile> UserProfile { get; set; }
        public virtual DbSet<Users> Users { get; set; }
        public virtual DbSet<webpages_Membership> webpages_Membership { get; set; }
        public virtual DbSet<webpages_OAuthMembership> webpages_OAuthMembership { get; set; }
        public virtual DbSet<webpages_Roles> webpages_Roles { get; set; }
    
        public virtual int AddOrUpdateSuperCallsData(Nullable<int> flag, string superCallString)
        {
            var flagParameter = flag.HasValue ?
                new ObjectParameter("flag", flag) :
                new ObjectParameter("flag", typeof(int));
    
            var superCallStringParameter = superCallString != null ?
                new ObjectParameter("SuperCallString", superCallString) :
                new ObjectParameter("SuperCallString", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("AddOrUpdateSuperCallsData", flagParameter, superCallStringParameter);
        }
    
        public virtual ObjectResult<string> AutoCompleteSymbol(Nullable<int> filetype, string optiontype)
        {
            var filetypeParameter = filetype.HasValue ?
                new ObjectParameter("filetype", filetype) :
                new ObjectParameter("filetype", typeof(int));
    
            var optiontypeParameter = optiontype != null ?
                new ObjectParameter("optiontype", optiontype) :
                new ObjectParameter("optiontype", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("AutoCompleteSymbol", filetypeParameter, optiontypeParameter);
        }
    
        public virtual int DeleteDataBeforeUpload(Nullable<int> fileNo, Nullable<int> fileType)
        {
            var fileNoParameter = fileNo.HasValue ?
                new ObjectParameter("FileNo", fileNo) :
                new ObjectParameter("FileNo", typeof(int));
    
            var fileTypeParameter = fileType.HasValue ?
                new ObjectParameter("FileType", fileType) :
                new ObjectParameter("FileType", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DeleteDataBeforeUpload", fileNoParameter, fileTypeParameter);
        }
    
        public virtual int DeleteDataForResult(Nullable<int> fileNo, Nullable<int> fileType)
        {
            var fileNoParameter = fileNo.HasValue ?
                new ObjectParameter("FileNo", fileNo) :
                new ObjectParameter("FileNo", typeof(int));
    
            var fileTypeParameter = fileType.HasValue ?
                new ObjectParameter("FileType", fileType) :
                new ObjectParameter("FileType", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DeleteDataForResult", fileNoParameter, fileTypeParameter);
        }
    
        public virtual int DeleteRecursiveFile(Nullable<int> fileType)
        {
            var fileTypeParameter = fileType.HasValue ?
                new ObjectParameter("FileType", fileType) :
                new ObjectParameter("FileType", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DeleteRecursiveFile", fileTypeParameter);
        }
    
        public virtual ObjectResult<string> ELMAH_GetErrorsXml(string application, Nullable<int> pageIndex, Nullable<int> pageSize, ObjectParameter totalCount)
        {
            var applicationParameter = application != null ?
                new ObjectParameter("Application", application) :
                new ObjectParameter("Application", typeof(string));
    
            var pageIndexParameter = pageIndex.HasValue ?
                new ObjectParameter("PageIndex", pageIndex) :
                new ObjectParameter("PageIndex", typeof(int));
    
            var pageSizeParameter = pageSize.HasValue ?
                new ObjectParameter("PageSize", pageSize) :
                new ObjectParameter("PageSize", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("ELMAH_GetErrorsXml", applicationParameter, pageIndexParameter, pageSizeParameter, totalCount);
        }
    
        public virtual ObjectResult<string> ELMAH_GetErrorXml(string application, Nullable<System.Guid> errorId)
        {
            var applicationParameter = application != null ?
                new ObjectParameter("Application", application) :
                new ObjectParameter("Application", typeof(string));
    
            var errorIdParameter = errorId.HasValue ?
                new ObjectParameter("ErrorId", errorId) :
                new ObjectParameter("ErrorId", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("ELMAH_GetErrorXml", applicationParameter, errorIdParameter);
        }
    
        public virtual int ELMAH_LogError(Nullable<System.Guid> errorId, string application, string host, string type, string source, string message, string user, string allXml, Nullable<int> statusCode, Nullable<System.DateTime> timeUtc)
        {
            var errorIdParameter = errorId.HasValue ?
                new ObjectParameter("ErrorId", errorId) :
                new ObjectParameter("ErrorId", typeof(System.Guid));
    
            var applicationParameter = application != null ?
                new ObjectParameter("Application", application) :
                new ObjectParameter("Application", typeof(string));
    
            var hostParameter = host != null ?
                new ObjectParameter("Host", host) :
                new ObjectParameter("Host", typeof(string));
    
            var typeParameter = type != null ?
                new ObjectParameter("Type", type) :
                new ObjectParameter("Type", typeof(string));
    
            var sourceParameter = source != null ?
                new ObjectParameter("Source", source) :
                new ObjectParameter("Source", typeof(string));
    
            var messageParameter = message != null ?
                new ObjectParameter("Message", message) :
                new ObjectParameter("Message", typeof(string));
    
            var userParameter = user != null ?
                new ObjectParameter("User", user) :
                new ObjectParameter("User", typeof(string));
    
            var allXmlParameter = allXml != null ?
                new ObjectParameter("AllXml", allXml) :
                new ObjectParameter("AllXml", typeof(string));
    
            var statusCodeParameter = statusCode.HasValue ?
                new ObjectParameter("StatusCode", statusCode) :
                new ObjectParameter("StatusCode", typeof(int));
    
            var timeUtcParameter = timeUtc.HasValue ?
                new ObjectParameter("TimeUtc", timeUtc) :
                new ObjectParameter("TimeUtc", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ELMAH_LogError", errorIdParameter, applicationParameter, hostParameter, typeParameter, sourceParameter, messageParameter, userParameter, allXmlParameter, statusCodeParameter, timeUtcParameter);
        }
    
        public virtual int GetChartData(string associateCode, Nullable<System.DateTime> startDate, Nullable<System.DateTime> endDate)
        {
            var associateCodeParameter = associateCode != null ?
                new ObjectParameter("associateCode", associateCode) :
                new ObjectParameter("associateCode", typeof(string));
    
            var startDateParameter = startDate.HasValue ?
                new ObjectParameter("startDate", startDate) :
                new ObjectParameter("startDate", typeof(System.DateTime));
    
            var endDateParameter = endDate.HasValue ?
                new ObjectParameter("endDate", endDate) :
                new ObjectParameter("endDate", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("GetChartData", associateCodeParameter, startDateParameter, endDateParameter);
        }
    
        public virtual ObjectResult<GetCTLDCTHDData_Result> GetCTLDCTHDData(Nullable<System.DateTime> expiryDate, Nullable<System.DateTime> workingDate, string optionType, Nullable<int> fileType, string symbol, string strikePrice)
        {
            var expiryDateParameter = expiryDate.HasValue ?
                new ObjectParameter("ExpiryDate", expiryDate) :
                new ObjectParameter("ExpiryDate", typeof(System.DateTime));
    
            var workingDateParameter = workingDate.HasValue ?
                new ObjectParameter("WorkingDate", workingDate) :
                new ObjectParameter("WorkingDate", typeof(System.DateTime));
    
            var optionTypeParameter = optionType != null ?
                new ObjectParameter("OptionType", optionType) :
                new ObjectParameter("OptionType", typeof(string));
    
            var fileTypeParameter = fileType.HasValue ?
                new ObjectParameter("FileType", fileType) :
                new ObjectParameter("FileType", typeof(int));
    
            var symbolParameter = symbol != null ?
                new ObjectParameter("Symbol", symbol) :
                new ObjectParameter("Symbol", typeof(string));
    
            var strikePriceParameter = strikePrice != null ?
                new ObjectParameter("StrikePrice", strikePrice) :
                new ObjectParameter("StrikePrice", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetCTLDCTHDData_Result>("GetCTLDCTHDData", expiryDateParameter, workingDateParameter, optionTypeParameter, fileTypeParameter, symbolParameter, strikePriceParameter);
        }
    
        public virtual ObjectResult<GetHotStockRecursiveUploadData_Result> GetHotStockRecursiveUploadData(Nullable<long> flag)
        {
            var flagParameter = flag.HasValue ?
                new ObjectParameter("flag", flag) :
                new ObjectParameter("flag", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetHotStockRecursiveUploadData_Result>("GetHotStockRecursiveUploadData", flagParameter);
        }
    
        public virtual ObjectResult<GetPDLPDHData_Result> GetPDLPDHData(Nullable<System.DateTime> expiryDate, Nullable<System.DateTime> workingDate, string optionType, Nullable<int> fileType, string symbol, string strikePrice)
        {
            var expiryDateParameter = expiryDate.HasValue ?
                new ObjectParameter("ExpiryDate", expiryDate) :
                new ObjectParameter("ExpiryDate", typeof(System.DateTime));
    
            var workingDateParameter = workingDate.HasValue ?
                new ObjectParameter("WorkingDate", workingDate) :
                new ObjectParameter("WorkingDate", typeof(System.DateTime));
    
            var optionTypeParameter = optionType != null ?
                new ObjectParameter("OptionType", optionType) :
                new ObjectParameter("OptionType", typeof(string));
    
            var fileTypeParameter = fileType.HasValue ?
                new ObjectParameter("FileType", fileType) :
                new ObjectParameter("FileType", typeof(int));
    
            var symbolParameter = symbol != null ?
                new ObjectParameter("Symbol", symbol) :
                new ObjectParameter("Symbol", typeof(string));
    
            var strikePriceParameter = strikePrice != null ?
                new ObjectParameter("StrikePrice", strikePrice) :
                new ObjectParameter("StrikePrice", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetPDLPDHData_Result>("GetPDLPDHData", expiryDateParameter, workingDateParameter, optionTypeParameter, fileTypeParameter, symbolParameter, strikePriceParameter);
        }
    
        public virtual ObjectResult<GetTDLTDHData_Result> GetTDLTDHData(Nullable<System.DateTime> expiryDate, Nullable<System.DateTime> workingDate, string optionType, Nullable<int> fileType, string symbol, string strikePrice, Nullable<int> noOfDayOfDataToBeTaken)
        {
            var expiryDateParameter = expiryDate.HasValue ?
                new ObjectParameter("ExpiryDate", expiryDate) :
                new ObjectParameter("ExpiryDate", typeof(System.DateTime));
    
            var workingDateParameter = workingDate.HasValue ?
                new ObjectParameter("WorkingDate", workingDate) :
                new ObjectParameter("WorkingDate", typeof(System.DateTime));
    
            var optionTypeParameter = optionType != null ?
                new ObjectParameter("OptionType", optionType) :
                new ObjectParameter("OptionType", typeof(string));
    
            var fileTypeParameter = fileType.HasValue ?
                new ObjectParameter("FileType", fileType) :
                new ObjectParameter("FileType", typeof(int));
    
            var symbolParameter = symbol != null ?
                new ObjectParameter("Symbol", symbol) :
                new ObjectParameter("Symbol", typeof(string));
    
            var strikePriceParameter = strikePrice != null ?
                new ObjectParameter("StrikePrice", strikePrice) :
                new ObjectParameter("StrikePrice", typeof(string));
    
            var noOfDayOfDataToBeTakenParameter = noOfDayOfDataToBeTaken.HasValue ?
                new ObjectParameter("NoOfDayOfDataToBeTaken", noOfDayOfDataToBeTaken) :
                new ObjectParameter("NoOfDayOfDataToBeTaken", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetTDLTDHData_Result>("GetTDLTDHData", expiryDateParameter, workingDateParameter, optionTypeParameter, fileTypeParameter, symbolParameter, strikePriceParameter, noOfDayOfDataToBeTakenParameter);
        }
    
        public virtual ObjectResult<mv9_varchar_table_Result> mv9_varchar_table(string companyname, string passeddate, Nullable<double> iDH, Nullable<double> idl)
        {
            var companynameParameter = companyname != null ?
                new ObjectParameter("companyname", companyname) :
                new ObjectParameter("companyname", typeof(string));
    
            var passeddateParameter = passeddate != null ?
                new ObjectParameter("passeddate", passeddate) :
                new ObjectParameter("passeddate", typeof(string));
    
            var iDHParameter = iDH.HasValue ?
                new ObjectParameter("IDH", iDH) :
                new ObjectParameter("IDH", typeof(double));
    
            var idlParameter = idl.HasValue ?
                new ObjectParameter("idl", idl) :
                new ObjectParameter("idl", typeof(double));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<mv9_varchar_table_Result>("mv9_varchar_table", companynameParameter, passeddateParameter, iDHParameter, idlParameter);
        }
    }
}
