//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BhagirathFincareClassLibrary.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RecursiveUpload
    {
        public int Id { get; set; }
        public string Symbol { get; set; }
        public Nullable<System.DateTime> ExpiryDate { get; set; }
        public string StrikePrice { get; set; }
        public string OptionType { get; set; }
        public string Open { get; set; }
        public string High { get; set; }
        public string Low { get; set; }
        public string Cmp { get; set; }
        public string Close { get; set; }
        public Nullable<int> FileType { get; set; }
        public Nullable<System.DateTime> UploadDateTime { get; set; }
        public Nullable<int> FileNo { get; set; }
        public string Average { get; set; }
        public string TotalTradeValue { get; set; }
    }
}
