//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BhagirathFincareClassLibrary.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SuperCallsData
    {
        public int Id { get; set; }
        public string SuperCallString { get; set; }
        public int flag { get; set; }
        public Nullable<System.DateTime> ModifiedDateTime { get; set; }
    }
}
