//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BhagirathFincareClassLibrary.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Users
    {
        public int Id { get; set; }
        public int UserId { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string UserName { get; set; }
        public string MobileNumber { get; set; }
        public string SessionId { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public System.DateTime LastUpadateDate { get; set; }
        public bool IsExpire { get; set; }
        public System.DateTime LastPaymentDate { get; set; }
        public int PaymentType { get; set; }
        public string Email { get; set; }
        public string SubscriptionType { get; set; }
        public bool IsAssociate { get; set; }
        public string ParentAssociateCode { get; set; }
        public string AssociateCode { get; set; }
        public Nullable<System.DateTime> BirthDate { get; set; }
        public bool AllowedEquity { get; set; }
        public bool AllowedCommodity { get; set; }
        public bool AllowedCurrency { get; set; }
        public string IPAddress { get; set; }
        public Nullable<bool> IsAdmin { get; set; }
        public Nullable<bool> AllowedHotStocks { get; set; }
        public Nullable<bool> AllowedSuperCallsEquity { get; set; }
        public Nullable<bool> AllowedSuperCallsCommodity { get; set; }
        public Nullable<bool> AllowedSuperCallsCurrency { get; set; }
    }
}
