<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Library</OutputType>
    <SccProjectName>SAK</SccProjectName>
    <SccLocalPath>SAK</SccLocalPath>
    <SccAuxPath>SAK</SccAuxPath>
    <SccProvider>SAK</SccProvider>
  </PropertyGroup>
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <AssemblyTitle>BhagirathFincareCore</AssemblyTitle>
    <Product>BhagirathFincareCore</Product>
    <Copyright>Copyright ©  2018</Copyright>
    <AssemblyVersion>1.0.0.0</AssemblyVersion>
    <FileVersion>1.0.0.0</FileVersion>
  </PropertyGroup>
  <ItemGroup>
    <Compile Remove="App_Start\**" />
    <EmbeddedResource Remove="App_Start\**" />
    <None Remove="App_Start\**" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\BhagirathFincareClassLibrary\BhagirathFincareClassLibrary.csproj" />
    <ProjectReference Include="..\BhagirathFincareUtil\BhagirathFincareUtil.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="BouncyCastle" Version="1.8.6.1" />
    <PackageReference Include="iTextSharp" Version="5.5.13.2" />
    <PackageReference Include="itextsharp.xmlworker" Version="5.5.13.2" />
    <PackageReference Include="log4net" Version="2.0.12" />
    <PackageReference Include="Microsoft.CSharp" Version="4.7.0" />
    <PackageReference Include="SelectListManager" Version="2.0.0" />
    <PackageReference Include="System.ComponentModel.Annotations" Version="5.0.0" />
    <PackageReference Include="System.Data.DataSetExtensions" Version="4.5.0" />
    <PackageReference Include="Microsoft.AspNetCore.SystemWebAdapters" Version="1.3.0" />
    <PackageReference Include="EntityFramework" Version="6.4.4" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
    <PackageReference Include="System.Configuration.ConfigurationManager" Version="8.0.0" />
  </ItemGroup>
</Project>